### ISSUE TITLE
Testing for M2 Batch 2

### ISSUE THREAD

**Issue by IshDeshpa** [lhr-solar/Controls#342]
- [x] ReadCarCAN Restructure Testing (once complete - https://github.com/lhr-solar/Controls/issues/308 )
- [x] Minion Driver Sanity Test (#310 )
- [x] SendCarCAN (#337 )
- [x] Motor Telemetry Timeout (#307 )
- [x] Test_SendTritium Macro Removal (#338 )
- [x] Full System Test (main.c) (#357 )
